export * as comment from './comment';
export * as friends from './friends';
export * from './me';
export * from './update';
export * from './setPrivacy';
export * from './getByTag';
export * from './findByUsername';
export * from './addGame';
export * from './deleteGame';
export * from './addSteam';
